[package]
name = "uml_state_machine"
version = "0.1.0"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blob-uuid = "0.3.1"
error-chain = "0.12.2"
log = "0.4.8"
